### ISSUE TITLE
preliminary lbrycrdd container

### ISSUE THREAD

**Issue by chamunks** [lbryio/lbry-docker#1]
The initial container for lbrycrdd should have the ability to launch, run, not get in the way, and be portable.

My initial release will be simple and on Ubuntu 18.04 and require as few dependencies as possible.

The main process should run in a non-root user state.

This container will run the latest binary release by default and eventually will be the template for tagged releases in the future.

**Comment by uLan08** [comment]
Hello, I would like to take this on.

**Comment by chamunks** [comment]
Solved in a parallel repository which is soon to replace this one.  https://github.com/lbryio/lbry-docker-rig
