### ISSUE TITLE
Chainquery: Upload baseline SQL database seed to lbryio S3 container.

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#15]
This will likely have to come as a question to the end user during initial setup to offer the user the ability to download our latest snapshot database checkpoint of the LBRY checkpoint.  

This stuff, should we decide to,  would be GPG signed as well as the repository itself.

**Comment by Leopere** [comment]
I need to zip and ship the base SQL seed and then run a sha256 sum on it, then what I'll do rather than downloading the entire blob to my local just GPG sign the seed's hash.

**Comment by Leopere** [comment]
The 14Gb data.zip
sha256sum data.zip
6c456f3c3687fab98b1bb3869578ccae1e5ccfd351f8907b3870d204a21ea82e  data.zip

**Comment by nikooo777** [comment]
am I needed for something? can I unassign this from me?

**Comment by Leopere** [comment]
This is mostly ready we just need to debug the mysql configuration issue and then automation can be setup for uploading latest checkpoint data.  This requires time from both @Leopere and @tiger5226

**Comment by tiger5226** [comment]
Sounds good! I think we need a bash script here to make sure we upload every x blocks, so the seed doesnt get too far behind. Is that done?

**Comment by Leopere** [comment]
I've added two functions to the [quick-bootstrap.sh here](https://github.com/lbryio/lbry-docker/blob/master/chainquery/quick-bootstrap.sh#L110-L123). 

It won't pick a specific number of blocks I was just thinking a cronjob in one of the LBRY dev nodes that uploads things automatically on a schedule.

**Comment by tiger5226** [comment]
yeah, blocks are 2.5 minutes apart on average so we can backup once a week and that should be fine.
