### ISSUE TITLE
All: Get access to https://hub.docker.com/r/lbryio/

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#17]
Need to arrange access to create repos for these containers for testing and eventual deployment.

Tagging @nikooo777 as I believe he's likely the one with access.

**Comment by nikooo777** [comment]
I do not have access to said platform, however it's possible that @kauffj has.

**Comment by kauffj** [comment]
I do not - @lyoshenka ?

**Comment by Leopere** [comment]
Closing this as it's unlikely to progress so I'm going to use GitLab this comes with a lot of side benefits such as CI/CD
