### ISSUE TITLE
All: Consider GitHub issue creation via go-github or alternative

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#23]
https://github.com/google/go-github read up and consider implementing this alongside `haste-it`  for reporting git issues fast and concisely.

**Comment by Leopere** [comment]
This isn't necessary but it is highly desirable.

**Comment by dangarthwaite** [comment]
What's this about?

**Comment by Leopere** [comment]
There are a few projects that I've run into over time where theres been a system in place to sanitize and report any logs along with create a github issue all with one command.  It's something that would be nice so that we could shortcut any Q&A during issue reporting and RCA's.
