### ISSUE TITLE
lbrynet-daemon: Armhf/Arm64 compiler containers.

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#28]
This is me just keeping note of something discussed in Slack where someone expressed interest in an armhf/arm64 container that compiles lbrynet-daemon from https://github.com/lbryio/lbry.

**Comment by Leopere** [comment]
https://resin.io/blog/building-arm-containers-on-any-x86-machine-even-dockerhub/

**Comment by kodxana** [comment]
@kodxana :)

**Comment by Leopere** [comment]
PR #54 addresses this and will be merged with the Refactor branch. Thanks to work between @EnigmaCurry and I.
