### ISSUE TITLE
[Chainquery] Upgrade from mysql TCP connections to direct .socket connection.

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#63]
Share socket from the mariadb container with the chainquery container via volumes then connect directly.

@nikooo777 mentioned in a slack message that we should be using `mysql.socket` via `mysqldsn="lbry:PASSWORD@unix(/var/run/mysqld/mysqld.sock)/chainquery"` in the [Chainquery configurator start.sh](https://github.com/lbryio/lbry-docker/blob/master/chainquery/stuff/start.sh#L8) 

Using a direct socket connection will require testing but should vastly improve query speeds and security.

**Comment by EnigmaCurry** [comment]
It should support socket and TCP, as socket cannot be used in multi-host setups.

**Comment by nikooo777** [comment]
Why  MariaDB btw? In production we use perconaDB.

Any considerable improvements?

Also if it's not easy to achieve we can stick to TCP, the speed improvements are minimal.

**Comment by EnigmaCurry** [comment]
@nikooo777 I've been testing with MySQL 5.7 (not MariaDB) 

https://github.com/lbryio/lbry-docker/blame/master/contrib/systemd-cloud-init.md#L97

I can test with perconaDB, is there a specific version I should use?

**Comment by Leopere** [comment]
> Why MariaDB btw? In production we use perconaDB.

Thanks for the reminder @nikooo777 I've opened a PR for a Percona swap. #69
