### ISSUE TITLE
[FeatureRequest] Add non alias versions of the run.sh commands if possible.

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#75]
https://github.com/lbryio/lbry-docker/tree/master/contrib contains a README that relies on a run.sh if we could have the vanilla commands somewhere available perhaps at the bottom or something it could be useful then just refer to the vanilla command guide reference next to the commands.

**Comment by EnigmaCurry** [comment]
You can use run.sh without the alias, you just need to specify the full path to it. 

Do you mean though that you would like a reference for the kubectl and helm commands that run.sh utilizes?

**Comment by Leopere** [comment]
> would like a reference for the kubectl and helm commands that run.sh utilizes?
Just want to kind of assume that in some cases we're teaching someone how to functionally do this from the ground up so that adoption can have a lower barrier to entry.

**Comment by EnigmaCurry** [comment]
I agree. It may make sense to make ancillary .md files to break this up a bit. Then I could add additional info that is not necessarily pertinent to the regular install.

Also, this is why the run.sh `exe` function exists. It logs every raw command to the screen before running it, so it is fully transparent what is going on.
