### ISSUE TITLE
preliminary lbrycrdd container

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbry-docker#8]
The initial container for lbrycrdd should have the ability to launch, run, not get in the way, and be portable.

My initial release will be simple and on Ubuntu 18.04 and require as few dependencies as possible.

The main process should run in a non-root user state.

This container will run the latest binary release by default and eventually will be the template for tagged releases in the future.

**Comment by nixc-us** [comment]
Baseline lbrycrd container has been created.

**Comment by Leopere** [comment]
baseline container created, this should allow someone to sync the blockchain as is.  However, it's far from release ready.
